# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [2]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix


(True,
 array([[2.+0.j, 2.-1.j],
        [2.+1.j, 3.+0.j]]))


## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [3]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


(True,
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.        +0.70710678j, -0.        -0.70710678j]]))

# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [4]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


array([ -7.+16.j,  -9.+22.j,  -9.+38.j, -11.+52.j])


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [5]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[-11. +28.j, -13. +34.j, -13. +66.j, -15. +80.j],
       [-15. +40.j, -17. +46.j, -17. +94.j, -19.+108.j],
       [-15.+104.j, -17.+126.j, -17.+142.j, -19.+172.j],
       [-19.+148.j, -21.+170.j, -21.+202.j, -23.+232.j]])

# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



# ANSWERS

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

In [14]:
# Define the matrix H
H = np.array([[3, 2+1j], [2-1j, 1]])

# Check if H is Hermitian
is_hermitian = np.allclose(H, H.conj().T)

if is_hermitian:
    print("The matrix H is Hermitian.")
    # Find eigenvalues if H is Hermitian
    eigenvalues = np.linalg.eigvalsh(H)
    print("Eigenvalues of H:", eigenvalues)
else:
    print("The matrix H is not Hermitian.")


The matrix H is Hermitian.
Eigenvalues of H: [-0.44948974  4.44948974]


## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.


In [15]:
# Define the matrix U
U = np.array([[1/np.sqrt(2), 1j/np.sqrt(2)], [1j/np.sqrt(2), 1/np.sqrt(2)]])

# Check if U is Unitary
is_unitary = np.allclose(np.dot(U, U.conj().T), np.eye(2))

if is_unitary:
    print("The matrix U is Unitary.")
else:
    print("The matrix U is not Unitary.")

# Compute UU†
UU_dagger = np.dot(U, U.conj().T)

print("UU†:")
print(UU_dagger)


The matrix U is Unitary.
UU†:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

In [9]:
# Define the complex vectors v and w
v = np.array([1+1j, 2-1j])
w = np.array([1-2j, 3])

# Compute the tensor product v ⊗ w
tensor_product_vw = np.outer(v, w)

print("Tensor product v ⊗ w:")
print(tensor_product_vw)


Tensor product v ⊗ w:
[[3.-1.j 3.+3.j]
 [0.-5.j 6.-3.j]]


## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

In [10]:
# Define the complex matrices M1 and M2
M1 = np.array([[0, 1], [1, 0]])
M2 = np.array([[1j, 0], [0, -1j]])

# Compute the tensor product M1 ⊗ M2
tensor_product_M1_M2 = np.kron(M1, M2)

print("Tensor product M1 ⊗ M2:")
print(tensor_product_M1_M2)


Tensor product M1 ⊗ M2:
[[0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]]


## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

In [ ]:
# Define the initial input state vector (|0>)
input_state = np.array([1, 0])

# Define the beamsplitter matrix (50/50 beamsplitter)
beamsplitter_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])

# Define the phase shifter matrix (phase shift of pi/2)
phase_shifter_matrix = np.array([[1, 0], [0, np.exp(1j * np.pi / 2)]])

# Define the identity matrix (for representing absence of a component)
identity_matrix = np.eye(2)

# Define the components of the Mach-Zehnder interferometer
# The interferometer consists of two beamsplitters and two phase shifters
component1 = beamsplitter_matrix
component2 = identity_matrix
component3 = phase_shifter_matrix
component4 = beamsplitter_matrix

# Propagate the input state vector through each component
output_state = np.dot(component4, np.dot(component3, np.dot(component2, np.dot(component1, input_state))))

print("Output state vector after passing through the Mach-Zehnder interferometer:")
print(output_state)


## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)


In [13]:
# Define the initial input state vector (|00>)
input_state = np.array([1, 0, 0, 0])

# Define the Hadamard gate matrix
Hadamard_gate = 1 / np.sqrt(2) * np.array([[1, 1], [1, -1]])

# Define the Oracle gate matrix (U_f)
Uf_gate = np.array([[0, 1, 0, 0],
                    [1, 0, 0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, -1]])

# Propagate the input state vector through the gates
# Apply Hadamard gate to first qubit
state_after_H = np.kron(Hadamard_gate, np.eye(2)) @ input_state

# Apply the Oracle gate to both qubits
state_after_Uf = Uf_gate @ state_after_H

# Apply Hadamard gate to first qubit again
state_after_second_H = np.kron(Hadamard_gate, np.eye(2)) @ state_after_Uf

# The final state vector represents the output state
output_state = state_after_second_H

print("Output state vector after passing through the circuit:")
print(output_state)


Output state vector after passing through the circuit:
[ 0.5  0.5 -0.5  0.5]
